### ISSUE TITLE
Completed Assignment 5

### ISSUE THREAD

**Issue by valeste** [valeste/Assignment-5#1]
I have completed assignment 5 for FISH 549. In this repository you will find an assignment-5.md file that displays the code I used to read the siscowet data, manipulate the data, create and exploratory figure, and create an expository figure. In addition there are comments throughout the file that I have added to describe my thought process.

**Comment by mdscheuerell** [comment]
Nice job, Celeste! And I appreciate you making a Markdown doc that includes some descriptions of what you did along with the code and figures.
